-- Seed the global curriculum once. IDs are stable and inserts are idempotent.

insert into public.topics (id,title,slug,description,order_index) values
  ('foundations-complexity','Time & Space Complexity','foundations-complexity','Reason about the cost of your code before you write more of it.',1),
  ('arrays','Arrays','arrays','Indexing, traversal, in-place operations and contiguous data.',2),
  ('strings','Strings','strings','Character frequency, parsing and string transformations.',3),
  ('basic-math','Basic Math','basic-math','Arithmetic patterns, divisibility and mathematical reasoning.',4),
  ('hashing','Hashing','hashing','Frequency, lookup and constant-time set membership patterns.',5),
  ('two-pointers','Two Pointers','two-pointers','Use coordinated indices to compress search space.',6),
  ('sliding-window','Sliding Window','sliding-window','Maintain a moving range over sequential data.',7),
  ('prefix-sum','Prefix Sum','prefix-sum','Turn repeated range queries into simple arithmetic.',8),
  ('binary-search','Binary Search','binary-search','Exploit monotonic structure to cut search space.',9),
  ('sorting','Sorting','sorting','Ordering as a primitive for search, grouping and greedy strategies.',10),
  ('linked-lists','Linked Lists','linked-lists','Pointers, mutation, traversal and structural manipulation.',11),
  ('stack','Stack','stack','LIFO structure for parsing, monotonicity and state.',12),
  ('queue','Queue','queue','FIFO structure and breadth-first processing.',13),
  ('heap','Heap','heap','Priority-based retrieval and top-k patterns.',14),
  ('trees','Trees','trees','Recursive structure, traversal and hierarchical state.',15),
  ('bst','Binary Search Tree','bst','Ordered tree invariants and search.',16),
  ('trie','Trie','trie','Prefix indexing for string and dictionary problems.',17),
  ('recursion','Recursion','recursion','Model repeated subproblems with a smaller state.',18),
  ('backtracking','Backtracking','backtracking','Enumerate constrained search spaces with pruning.',19),
  ('greedy','Greedy','greedy','Build locally optimal choices under a provable invariant.',20),
  ('graphs','Graph Traversal','graphs','Represent relationships and systematically explore them.',21),
  ('shortest-paths','Shortest Paths','shortest-paths','Weighted and unweighted pathfinding.',22),
  ('union-find','Union Find','union-find','Track connectivity under incremental merges.',23),
  ('topological-sort','Topological Sort','topological-sort','Order dependency graphs with directed acyclic structure.',24),
  ('dynamic-programming','Dynamic Programming','dynamic-programming','Reuse overlapping subproblem results systematically.',25),
  ('advanced-dp','Advanced DP','advanced-dp','State compression, dimensions and harder transitions.',26)
on conflict (id) do update set title=excluded.title, slug=excluded.slug, description=excluded.description, order_index=excluded.order_index;

insert into public.topic_prerequisites (topic_id, prerequisite_topic_id) values
  ('arrays','foundations-complexity'),
  ('strings','arrays'),
  ('basic-math','strings'),
  ('hashing','basic-math'),
  ('two-pointers','hashing'),
  ('sliding-window','two-pointers'),
  ('prefix-sum','sliding-window'),
  ('binary-search','prefix-sum'),
  ('sorting','binary-search'),
  ('linked-lists','sorting'),
  ('stack','linked-lists'),
  ('queue','stack'),
  ('heap','queue'),
  ('trees','heap'),
  ('bst','trees'),
  ('trie','bst'),
  ('recursion','trie'),
  ('backtracking','recursion'),
  ('greedy','backtracking'),
  ('graphs','greedy'),
  ('shortest-paths','graphs'),
  ('union-find','shortest-paths'),
  ('topological-sort','union-find'),
  ('dynamic-programming','topological-sort'),
  ('advanced-dp','dynamic-programming')
on conflict do nothing;

insert into public.problems (id,topic_id,title,difficulty,platform,url,required,order_index) values
  ('p-000','foundations-complexity','Complexity Analysis: Time & Space','EASY','Big-O Cheat Sheet','https://www.bigocheatsheet.com/',true,1),
  ('p-001','arrays','Contains Duplicate','EASY','LeetCode','https://leetcode.com/problems/contains-duplicate/',true,1),
  ('p-002','arrays','Best Time to Buy and Sell Stock','EASY','LeetCode','https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',true,2),
  ('p-003','arrays','Product of Array Except Self','MEDIUM','LeetCode','https://leetcode.com/problems/product-of-array-except-self/',true,3),
  ('p-004','arrays','Maximum Subarray','MEDIUM','LeetCode','https://leetcode.com/problems/maximum-subarray/',true,4),
  ('p-005','strings','Valid Palindrome','EASY','LeetCode','https://leetcode.com/problems/valid-palindrome/',true,1),
  ('p-006','strings','Longest Common Prefix','EASY','LeetCode','https://leetcode.com/problems/longest-common-prefix/',true,2),
  ('p-007','strings','Encode and Decode Strings','MEDIUM','LeetCode','https://leetcode.com/problems/encode-and-decode-strings/',true,3),
  ('p-008','basic-math','Happy Number','EASY','LeetCode','https://leetcode.com/problems/happy-number/',true,1),
  ('p-009','hashing','Two Sum','EASY','LeetCode','https://leetcode.com/problems/two-sum/',true,1),
  ('p-010','hashing','Valid Anagram','EASY','LeetCode','https://leetcode.com/problems/valid-anagram/',true,2),
  ('p-011','hashing','Group Anagrams','MEDIUM','LeetCode','https://leetcode.com/problems/group-anagrams/',true,3),
  ('p-012','hashing','Top K Frequent Elements','MEDIUM','LeetCode','https://leetcode.com/problems/top-k-frequent-elements/',true,4),
  ('p-013','hashing','Longest Consecutive Sequence','MEDIUM','LeetCode','https://leetcode.com/problems/longest-consecutive-sequence/',true,5),
  ('p-014','hashing','Subarray Sum Equals K','MEDIUM','LeetCode','https://leetcode.com/problems/subarray-sum-equals-k/',true,6),
  ('p-015','hashing','Valid Sudoku','MEDIUM','LeetCode','https://leetcode.com/problems/valid-sudoku/',true,7),
  ('p-016','two-pointers','Two Sum II','MEDIUM','LeetCode','https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/',true,1),
  ('p-017','two-pointers','3Sum','MEDIUM','LeetCode','https://leetcode.com/problems/3sum/',true,2),
  ('p-018','two-pointers','Container With Most Water','MEDIUM','LeetCode','https://leetcode.com/problems/container-with-most-water/',true,3),
  ('p-019','sliding-window','Longest Substring Without Repeating Characters','MEDIUM','LeetCode','https://leetcode.com/problems/longest-substring-without-repeating-characters/',true,1),
  ('p-020','sliding-window','Longest Repeating Character Replacement','MEDIUM','LeetCode','https://leetcode.com/problems/longest-repeating-character-replacement/',true,2),
  ('p-021','prefix-sum','Range Sum Query','EASY','LeetCode','https://leetcode.com/problems/range-sum-query-immutable/',true,1),
  ('p-022','prefix-sum','Subarray Sum','MEDIUM','LeetCode','https://leetcode.com/problems/subarray-sum-equals-k/',true,2),
  ('p-023','binary-search','Binary Search','EASY','LeetCode','https://leetcode.com/problems/binary-search/',true,1),
  ('p-024','binary-search','Search a 2D Matrix','MEDIUM','LeetCode','https://leetcode.com/problems/search-a-2d-matrix/',true,2),
  ('p-025','binary-search','Koko Eating Bananas','MEDIUM','LeetCode','https://leetcode.com/problems/koko-eating-bananas/',true,3),
  ('p-026','sorting','Merge Intervals','MEDIUM','LeetCode','https://leetcode.com/problems/merge-intervals/',true,1),
  ('p-027','sorting','Sort Colors','MEDIUM','LeetCode','https://leetcode.com/problems/sort-colors/',true,2),
  ('p-028','linked-lists','Reverse Linked List','EASY','LeetCode','https://leetcode.com/problems/reverse-linked-list/',true,1),
  ('p-029','linked-lists','Merge Two Sorted Lists','EASY','LeetCode','https://leetcode.com/problems/merge-two-sorted-lists/',true,2),
  ('p-030','stack','Valid Parentheses','EASY','LeetCode','https://leetcode.com/problems/valid-parentheses/',true,1),
  ('p-031','stack','Daily Temperatures','MEDIUM','LeetCode','https://leetcode.com/problems/daily-temperatures/',true,2),
  ('p-032','queue','Number of Islands (BFS)','MEDIUM','LeetCode','https://leetcode.com/problems/number-of-islands/',true,1),
  ('p-033','heap','Kth Largest Element in an Array','MEDIUM','LeetCode','https://leetcode.com/problems/kth-largest-element-in-an-array/',true,1),
  ('p-034','trees','Invert Binary Tree','EASY','LeetCode','https://leetcode.com/problems/invert-binary-tree/',true,1),
  ('p-035','trees','Maximum Depth of Binary Tree','EASY','LeetCode','https://leetcode.com/problems/maximum-depth-of-binary-tree/',true,2),
  ('p-036','trees','Binary Tree Level Order Traversal','MEDIUM','LeetCode','https://leetcode.com/problems/binary-tree-level-order-traversal/',true,3),
  ('p-037','bst','Validate Binary Search Tree','MEDIUM','LeetCode','https://leetcode.com/problems/validate-binary-search-tree/',true,1),
  ('p-038','trie','Implement Trie','MEDIUM','LeetCode','https://leetcode.com/problems/implement-trie-prefix-tree/',true,1),
  ('p-039','recursion','Subsets','MEDIUM','LeetCode','https://leetcode.com/problems/subsets/',true,1),
  ('p-040','backtracking','Combination Sum','MEDIUM','LeetCode','https://leetcode.com/problems/combination-sum/',true,1),
  ('p-041','greedy','Jump Game','MEDIUM','LeetCode','https://leetcode.com/problems/jump-game/',true,1),
  ('p-042','graphs','Clone Graph','MEDIUM','LeetCode','https://leetcode.com/problems/clone-graph/',true,1),
  ('p-043','graphs','Course Schedule','MEDIUM','LeetCode','https://leetcode.com/problems/course-schedule/',true,2),
  ('p-044','shortest-paths','Network Delay Time','MEDIUM','LeetCode','https://leetcode.com/problems/network-delay-time/',true,1),
  ('p-045','union-find','Redundant Connection','MEDIUM','LeetCode','https://leetcode.com/problems/redundant-connection/',true,1),
  ('p-046','topological-sort','Course Schedule II','MEDIUM','LeetCode','https://leetcode.com/problems/course-schedule-ii/',true,1),
  ('p-047','dynamic-programming','Climbing Stairs','EASY','LeetCode','https://leetcode.com/problems/climbing-stairs/',true,1),
  ('p-048','dynamic-programming','House Robber','MEDIUM','LeetCode','https://leetcode.com/problems/house-robber/',true,2),
  ('p-049','advanced-dp','Minimum Path Sum','MEDIUM','LeetCode','https://leetcode.com/problems/minimum-path-sum/',true,1)
on conflict (id) do update set topic_id=excluded.topic_id, title=excluded.title, difficulty=excluded.difficulty, platform=excluded.platform, url=excluded.url, required=excluded.required, order_index=excluded.order_index;

insert into public.problem_dependencies (problem_id, prerequisite_problem_id)
select p.id, prev.id from public.problems p join public.problems prev on prev.topic_id=p.topic_id and prev.order_index=p.order_index-1
on conflict do nothing;

insert into public.resources (id,topic_id,title,type,source,url,order_index) values
  ('r-1','arrays','Arrays Fundamentals','NOTES','DSA Notes','https://www.geeksforgeeks.org/array-data-structure/',1),
  ('r-2','arrays','Array Techniques','VIDEO','NeetCode','https://www.youtube.com/@NeetCode',2),
  ('r-3','hashing','Hashing Fundamentals','NOTES','USACO Guide','https://usaco.guide/',1),
  ('r-4','hashing','Hash Tables Explained','VIDEO','NeetCode','https://www.youtube.com/@NeetCode',2),
  ('r-5','hashing','C++ unordered_map','REFERENCE','cppreference','https://en.cppreference.com/w/cpp/container/unordered_map',3),
  ('r-6','two-pointers','Two Pointers Pattern','ARTICLE','NeetCode','https://neetcode.io/roadmap',1),
  ('r-7','sliding-window','Sliding Window Pattern','ARTICLE','NeetCode','https://neetcode.io/roadmap',1),
  ('r-8','trees','Tree Traversals','REFERENCE','cppreference','https://en.cppreference.com/',1),
  ('r-9','graphs','Graph Traversal','VIDEO','William Fiset','https://www.youtube.com/@WilliamFiset',1),
  ('r-10','dynamic-programming','Dynamic Programming Notes','NOTES','cp-algorithms','https://cp-algorithms.com/dynamic_programming/intro-to-dp.html',1)
on conflict (id) do update set topic_id=excluded.topic_id, title=excluded.title, type=excluded.type, source=excluded.source, url=excluded.url, order_index=excluded.order_index;